"""Help text parity (UNIFY 5.3 tooltips, 5.7 tutorial).

Extracts, from legacy_client/client.py:
  - STEPS in TaskipelagoApp._open_tutorial
  - every `_<name>_tip = "..."` string and `Tooltip(_<name>, "...")` text in build_ui
and writes web-client/js/generator/legacy_text.js, so the web generator shows
the legacy text byte for byte:

    python tests/parity/legacy_text.py

tests/python/test_legacy_text.py fails when the JS file is out of date.
Web-only text lives in the modules that use it, not in the generated file.
"""
from __future__ import annotations

import ast
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CLIENT = ROOT / "legacy_client" / "client.py"
OUT = ROOT / "custom_worlds" / "taskipelago" / "web-client" / "js" / "generator" / "legacy_text.js"


def _method(tree: ast.AST, name: str) -> ast.FunctionDef:
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == name:
            return node
    raise RuntimeError(f"{name} not found")


def legacy_steps(tree: ast.AST) -> list:
    for stmt in ast.walk(_method(tree, "_open_tutorial")):
        if isinstance(stmt, ast.Assign) and any(getattr(t, "id", None) == "STEPS" for t in stmt.targets):
            return [list(step) for step in ast.literal_eval(stmt.value)]
    raise RuntimeError("STEPS not found in _open_tutorial")


def legacy_tips(tree: ast.AST) -> dict:
    tips = {}
    for stmt in ast.walk(_method(tree, "build_ui")):
        if (isinstance(stmt, ast.Assign) and len(stmt.targets) == 1
                and isinstance(stmt.targets[0], ast.Name) and stmt.targets[0].id.endswith("_tip")):
            tips[stmt.targets[0].id.strip("_")[:-len("_tip")]] = ast.literal_eval(stmt.value)
        elif (isinstance(stmt, ast.Call) and getattr(stmt.func, "id", None) == "Tooltip"
                and isinstance(stmt.args[0], ast.Name)):
            tips[stmt.args[0].id.strip("_")] = ast.literal_eval(stmt.args[1])
    return tips


NAME_RULE = ("must start with a letter or underscore and must not contain digits, spaces,\n"
             "quotes, parentheses, commas, && or ||.")
# Intentional v1.1 text changes applied on top of the legacy text: {key: [(old, new)]}.
V11_TIP_CHANGES = {
    # F8: unified region / progressive group name rule.
    "pg_hint": [("may only contain letters, underscores, and hyphens - no digits.", NAME_RULE)],
    "rg_hint": [("may only contain letters, underscores, and hyphens - no digits.", NAME_RULE)],
}


def v11_tips(tree: ast.AST) -> dict:
    tips = legacy_tips(tree)
    for key, changes in V11_TIP_CHANGES.items():
        for old, new in changes:
            assert old in tips[key], (key, old)
            tips[key] = tips[key].replace(old, new)
    return tips


def render() -> str:
    tree = ast.parse(CLIENT.read_text(encoding="utf-8"))
    dump = lambda s: json.dumps(s, ensure_ascii=True)  # noqa: E731
    lines = [
        "// GENERATED by tests/parity/legacy_text.py from legacy_client/client.py.",
        "// Do not edit: regenerate after changing the legacy text or V11_TIP_CHANGES.",
        "",
        "// _open_tutorial STEPS: [title, text]",
        "export const LEGACY_STEPS = [",
    ]
    for title, content in legacy_steps(tree):
        lines.append(f"  [{dump(title)},")
        lines.append(f"    {dump(content)}],")
    lines += ["];", "", "// build_ui tooltips, keyed by the legacy variable name", "export const TIPS = {"]
    for key, text in sorted(v11_tips(tree).items()):
        lines.append(f"  {key}: {dump(text)},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
